### ISSUE TITLE
Move this repository to the attic

### ISSUE THREAD

**Issue by michaelsembwever** [openzipkin-attic/zipkin-azure#52]
As part of the move to the Apache Software Foundation this repository will transfer ownership to `apache` and name to `incubator-zipkin-azure`.

See https://issues.apache.org/jira/browse/INFRA-16989

**Comment by codefromthecrypt** [comment]
We've had a chat and think that this repo should move to contrib, as no one is improving it and it is pure maintenance. If something changes later we could consider starting again in apache.

cc @openzipkin/core @aliostad

**Comment by codefromthecrypt** [comment]
I will move this to the attic tomorrow and click archive
